<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           min="0"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                    <a class="cart_quantity_down" href="javascript:void(0)" id="decrementQty"></a>
                    <a class="cart_quantity_up" href="javascript:void(0);" id="incrementQty"></a>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
    <script>
        require([
            'jquery'
    ],
    function ($) {
        $("#decrementQty").click(function(event) {
            event.preventDefault();
            var val = parseInt($("#qty").val());
            if(val != 1)
            document.getElementById("qty").value = val - 1;
            $("#qty").trigger("change");

        });
        $("#incrementQty").click(function(event) {
            event.preventDefault();
            var val = parseInt($("#qty").val());
            document.getElementById("qty").value = val + 1;
            $("#qty").trigger("change");

        });
    });
    </script>

<?php endif; ?>
