<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
$helper = $this->helper('Thecommerceshop\Theme\Helper\Data');
?>
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <?php if($helper->isLoggedIn()) { ?>
            <span class="logged-in">Welcome, <?php echo $helper->getCustomerName(); ?>!</span>
        <?php } ?>
        <!-- ko ifnot: customer().fullname  -->
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
<script>
    require(['jquery'],function($){

        $('.phone a').on('click', function(){
            $('#zsiq_agtpic').click();
        });

    });
</script>
