<li class="wishlist" data-bind="scope: 'wishlist'">
    <!-- <a href="<?php //echo $this->getUrl('wishlist') ?>"><i class="fa fa-heart-o" aria-hidden="true"></i></a> -->
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="wishlist-custom">
        <span class="text"><i class="fa fa-heart-o" aria-hidden="true"></i></span>
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>