
<div>
 <div class="top-header">	
  <div class="row">	
		<div class="top-left d-flex">
			<p><?php echo $this->helper('Thecommerceshop\Theme\Helper\Data')->getConfigValue('design/header/welcome'); ?></p>
		</div>
		<div class="top-middle d-flex">
			<?php
				echo $this->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('topline-links')
						->toHtml();
			?>
		</div>
		<!-- <div class="top-right d-flex">
			<div class="follow_us d-flex">
				<a href="https://www.facebook.com/SchoolArtShowsbyArtome/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a>
				<a href="https://twitter.com/artomeartshows?lang=en" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
				<a href="https://in.pinterest.com/sabrinaar/artome/" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i>Pinterest</a>
				<a href="https://www.artomeplus.com/" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i>Gmail</a>
			</div>	
			
		</div>	 -->
   </div>
  </div>	
<div>	
